[[chapter2]]
== Word/Doubleword/Quadword CAS (AMOCAS.W/D/Q)

[wavedrom, , ] 
.... 
{reg: [
  {bits:  7, name: 'opcode', attr:'AMO'},
  {bits:  5, name: 'rd', attr:'dest'},
  {bits:  3, name: 'funct3', attr:['010', '011', '100']},
  {bits:  5, name: 'rs1', attr:'addr'},
  {bits:  5, name: 'rs2', attr:'src'},
  {bits:  1, name: 'rl'},
  {bits:  1, name: 'aq'},
  {bits:  5, name: '00101', attr:['AMOCAS.W', 'AMOCAS.D', 'AMOCAS.Q']},
], config:{lanes: 1, hspace:1024}}
....

`AMOCAS.W` atomically loads 32-bits of a data value from address in `rs1`,
compares the loaded value to a 32-bit value held in `rd` and if the
comparison is bitwise equal, then stores the 32-bit value held in `rs2` to
the original address in `rs1`. The value loaded from memory is placed into
register `rd`. For RV64, `AMOCAS.W` always sign-extends the value placed in
`rd`, and ignores the upper 32 bits of the original value in `rd` and `rs2`.
The operation performed by `AMOCAS.W` is as follows:

[source, ruby]
----
    temp = *[rs1]
    if temp == [rd]
        *[rs1] = [rs2]
    endif
    [rd] = temp
----

`AMOCAS.D` is similar to `AMOCAS.W` but operates on 64-bit data values.

For RV32, `AMOCAS.D` atomically loads 64-bits of a data value from address in
`rs1`, compares the loaded value to a 64-bits value held in a register pair
consisting of `rd` and `rd+1` and if the comparison is bitwise equal, then
stores the 64-bit value held in the register pair `rs2` and `rs2+1` to the
original address in `rs1`. The value loaded from memory is placed into the
register pair `rd` and `rd+1`. The instruction requires the first register in
the pair to be even numbered; encodings with odd numbered registers specified
in `rs2` and `rd` are reserved. When the first register of a source register
pair is `x0`, then both halves of the pair read as zero. When the first
register of a destination register pair is `x0`, then the entire register
result is discarded and neither destination register is written.
The operation performed by `AMOCAS.D` for RV32 is as follows:
[source, ruby]
----
    temp0 = *([rs1]+0)
    temp1 = *([rs1]+4)
    comp0 = (rd == x0)  ? 0 : [rd]
    comp1 = (rd == x0)  ? 0 : [rd+1]
    swap0 = (rs2 == x0) ? 0 : [rs2]
    swap1 = (rs2 == x0) ? 0 : [rs2+1]
    if (temp0 == comp0) && (temp1 == comp1)
        *([rs1]+0) = swap0
        *([rs1]+4) = swap1
    endif
    if ( rd != x0 )
        [rd]   = temp0
        [rd+1] = temp1
    endif
----

For RV64, `AMOCAS.D` atomically loads 64-bits of a data value from address in
`rs1`, compares the loaded value to a 64-bit value held in `rd` and if the
comparison is bitwise equal, then stores the 64-bit value held in `rs2` to the
original address in `rs1`. The value loaded from memory is placed into register
`rd`. The operation performed by `AMOCAS.D` for RV64 is as follows:
[source, ruby]
----
    temp = *[rs1]
    if temp == [rd]
        *[rs1] = [rs2]
    endif
    [rd] = temp
----
`AMOCAS.Q` (RV64 only) atomically loads 128-bits of a data value from address in
`rs1`, compares the loaded value to a 128-bits value held in a register pair
consisting of `rd` and `rd+1` and if the comparison is bitwise equal, then
stores the 128-bit value held in the register pair `rs2` and `rs2+1` to the
original address in `rs1`. The value loaded from memory is placed into the
register pair `rd` and `rd+1`. The instruction requires the first register in
the pair to be even numbered; encodings with odd numbered registers specified in
`rs2` and `rd` are reserved. When the first register of a source register pair
is `x0`, then both halves of the pair read as zero. When the first register of a
destination register pair is `x0`, then the entire register result is discarded
and neither destination register is written. The operation performed by
`AMOCAS.Q` is as follows:
[source, ruby]
----
    temp0 = *([rs1]+0)
    temp1 = *([rs1]+8)
    comp0 = (rd == x0)  ? 0 : [rd]
    comp1 = (rd == x0)  ? 0 : [rd+1]
    swap0 = (rs2 == x0) ? 0 : [rs2]
    swap1 = (rs2 == x0) ? 0 : [rs2+1]
    if (temp0 == comp0) && (temp1 == comp1)
        *([rs1]+0) = swap0
        *([rs1]+8) = swap1
    endif
    if ( rd != x0 )
        [rd]   = temp0
        [rd+1] = temp1
    endif
----
[NOTE]
====
For a future RV128 extension, `AMOCAS.Q` would encode a single XLEN=128 register
in `rs2` and `rd`.
====
Just as for AMOs in the A extension, `AMOCAS.W/D/Q` requires that the address
held in `rs1` be naturally aligned to the size of the operand (i.e., 16-byte
aligned for _quadwords_, eight-byte aligned for _doublewords_, and four-byte
aligned for _words_). And the same exception options apply if the address is not
naturally aligned.

Just as for AMOs in the A extension, the `AMOCAS.W/D/Q` optionally provide
release consistency semantics, using the `aq` and `rl` bits, to help implement
multiprocessor synchronization.

== Additional AMO PMAs

There are four levels of PMA support defined for AMOs in the A extension. Zacas
defines three additional levels of support: `AMOCasW`, `AMOCasD`, and `AMOCasQ`.

`AMOCasW` indicates that in addition to instructions indicated by `AMOArithmetic`
level support, the `AMOCAS.W` instruction is supported. `AMOCasD` indicates that
in addition to instructions indicated by `AMOCasW` level support, the `AMOCAS.D`
instruction is supported. `AMOCasQ` indicates that all RISC-V AMOs are supported.

[NOTE]
====
`AMOCasW/D/Q` require `AMOArithmetic` level support as the `AMOCAS.W/D/Q`
instructions require ability to perform an arithmetic comparison and a swap
operation. 
====

